CREATE TABLE llx_lmdbwurthpunchout_session_line (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer DEFAULT 1 NOT NULL,
	fk_session integer NOT NULL,
	line_index integer DEFAULT 0 NOT NULL,
	vendor_ref varchar(128) NOT NULL,
	external_id varchar(128) NULL,
	label varchar(255) NULL,
	description text NULL,
	qty double(24,8) DEFAULT 0 NOT NULL,
	unit_code varchar(32) NULL,
	fk_unit integer NULL,
	price double(24,8) DEFAULT 0 NOT NULL,
	price_unit double(24,8) DEFAULT 1 NOT NULL,
	unit_price_ht double(24,8) DEFAULT 0 NOT NULL,
	currency varchar(3) DEFAULT 'EUR' NOT NULL,
	leadtime_days integer DEFAULT 0 NOT NULL,
	vat_rate double(6,3) DEFAULT 0 NOT NULL,
	fk_product integer NULL,
	fk_product_fournisseur_price integer NULL,
	fk_commandefourndet integer NULL,
	warning text NULL
) ENGINE=innodb;
